---
version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: "[%(asctime)s][%(levelname)8s][%(filename)15s][%(lineno)4d][%(funcName)s][%(message)s]"
    datefmt: "%Y-%m-%d %H:%M:%S"

  original:
    format: "%(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: sys.stdout

  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/log/info.log
    mode: a

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: logs/log/error.log
    mode: a

  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/log/debug.log
    mode: a

  stability_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: original
    filename: logs/log/stability.json
    mode: a

  check_listen_ports_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: original
    filename: logs/log/check_listen_ports.log
    mode: a

loggers:
  steps:
    level: DEBUG
    handlers:
      - error_file_handler
      - debug_file_handler

  lib:
    level: DEBUG
    handlers:
      - error_file_handler
      - debug_file_handler

  environment:
    level: DEBUG
    handlers:
      - error_file_handler
      - debug_file_handler

  paramiko.transport:
    level: INFO
    handlers:
      - debug_file_handler

  root:
    level: DEBUG
    handlers:
      - error_file_handler
      - debug_file_handler

  stability:
    level: INFO
    handlers:
      - stability_file_handler

  check_listen_ports:
    level: INFO
    handlers:
      - check_listen_ports_file_handler